### ISSUE TITLE
Add pretty printing as an optional paramater to the JSON Response

### ISSUE THREAD

**Issue by lewismc** [lewismc/iPReS#23]
Right now we get a JSON response object and there is no option to pretty print it so it is difficult to interpret at a glance.
We should consider implementing something like
https://clojuredocs.org/clojure.pprint
as a mechanism for improving aesthetics and interpretation.

**Comment by cartermp** [comment]
I took a look at this a while back and again this morning, and it seems to be difficult to do.  Running the data set through pprint would actually just insert a ton of tabs and spaces which would result in horrendous output because ring interprets those as literal characters.  I can't seem to find a middleware support pretty-printing at this time.

**Comment by lewismc** [comment]
I also had a look and found it hellish to implement. This has to do with support for this kind of thing within Clojure I think. I am +1 for leaving it and closing it off.
